# roles/sqlite/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create SQLite directory
  file:
    path: "{{ openio_sqlite_directory }}"
    owner: "{{ openio_sqlite_user }}"
    group: "{{ openio_sqlite_group }}"
    mode: 0755
    state: directory

- name: Create SQLite databases
  file:
    name: "{{ openio_sqlite_directory }}/{{ item }}.db"
    owner: "{{ openio_sqlite_user }}"
    group: "{{ openio_sqlite_group }}"
    mode: 0644
    state: touch
  with_items: "{{ openio_sqlite_databases }}"
  changed_when: false
...
